### 1 задание
  Первые три колонки - это год, месяц и день. Остальные 12 колонок - скорость   ветра, измеренная в узлах, в 12 реперных точках, разбросанных по всей Ирландии.

   В файле присутствуют комментарии, описывающие датасет. Комментарии начинаются  с символа '%'. При загрузке датасета очистите его от всех комментариев. 

   Используйте функцию 'np.loadtxt' для загрузки датасета в numpy массив.

In [118]:
from calendar import month

import numpy as np
from numpy.ma.core import reshape

df = np.loadtxt(fname='wind-data-1969.csv', comments='%', delimiter=',')
print(df)

[[ 0.    1.    1.   ...  6.34  9.17 16.71]
 [ 0.    1.    2.   ...  5.41  8.17 13.29]
 [69.    1.    3.   ...  7.25 11.96 16.17]
 ...
 [69.   12.   29.   ...   nan 13.75 25.04]
 [69.   12.   30.   ... 11.42 11.5  27.84]
 [69.   12.   31.   ...  7.12 11.17 17.41]]


### 2 задание
Все измерения были сделаны и записаны вручную, поэтому у нескольких записей  отсутствуют ожидаемые значения. Всего существует два типа ошибок заполнения: 
 * При заполнении не был указан год, тогда значение в первой колонке будет  равно 0. Заполните отсутствующие значения года самостоятельно.
 * Были дни, когда не удавалось снять значение со всех реперных точек.  В этом случае в местах отсутствия измерений стоит NaN.  Заполните недостающие значения средним значением в этой точке. 
 (Подсказка: используйте функции np.nanmean для подсчета среднего, игнорируя np.nan, и np.isnan для создания маски выборки)

> В этом пункте разрешается использования цикла for.

In [119]:
for dayData in df:
    average = np.nanmean(dayData[3:])
    maskArr = np.isnan(dayData)
    for i in range(0, len(dayData)):
        if maskArr[i]:
            dayData[i] = average
    if dayData[0] == 0:
        dayData[0] = 69
df

array([[69.        ,  1.        ,  1.        , ...,  6.34      ,
         9.17      , 16.71      ],
       [69.        ,  1.        ,  2.        , ...,  5.41      ,
         8.17      , 13.29      ],
       [69.        ,  1.        ,  3.        , ...,  7.25      ,
        11.96      , 16.17      ],
       ...,
       [69.        , 12.        , 29.        , ..., 14.46545455,
        13.75      , 25.04      ],
       [69.        , 12.        , 30.        , ..., 11.42      ,
        11.5       , 27.84      ],
       [69.        , 12.        , 31.        , ...,  7.12      ,
        11.17      , 17.41      ]])

### 3 задание
Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, по всем реперным точкам за все дни (каждое значение считается относительно всего сета). Выведите полученные 4 значения.

In [120]:
data = df[:,3:]
print("Минимальное: ", data.min())
print("Максимальное: ",data.max())
print("Среднее: ",data.mean())
print("Среднее квадратическое отклонение: ",data.std())

Минимальное:  0.04
Максимальное:  38.2
Среднее:  9.498506171302063
Среднее квадратическое отклонение:  5.381868813462154


### 4 задание
Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, каждой реперной точки по всем дням. Для каждой точки должен получиться свой набор значений. Выведите полученные значения.

In [121]:
data = df[:, 3:]
print("Минимальное: ", data.min(axis=0))
print("Максимальное: ", data.max(axis=0))
print("Среднее: ", data.mean(axis=0))
print("Среднее квадратическое отклонение: ", data.std(axis=0))

Минимальное:  [0.67 0.54 2.17 0.21 2.04 0.04 0.21 0.25 0.5  0.13 1.58 2.21]
Максимальное:  [27.79       27.33       32.71       17.71636364 24.25       18.545
 27.71       21.92       22.04       20.38       31.88       38.2       ]
Среднее:  [11.16635616  9.69159051 10.81461594  5.96278021  9.86095522  6.33639626
  8.59195669  7.80095035  8.02253499  7.84439004 12.47846672 15.41108095]
Среднее квадратическое отклонение:  [5.3040624  5.17281304 4.73861036 3.25179102 4.34687833 3.57641763
 4.37609501 4.13674375 4.09545982 3.95269354 5.55709967 6.98483729]


### 5 задание
Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, всех реперных точек для каждого дня. Должен получиться свой набор значений для каждого дня.  

Добавьте в датасет новую колонку с максимальными значениями по дням.    

> Подсказка: используйте функции np.hstack и np.reshape

Выведите полученные значения.

In [122]:
print("Минимальное: ", data.min(axis=1))
maxForRows = data.max(axis=1)
print("Максимальное: ", maxForRows)
print("Среднее: ", data.mean(axis=1))
print("Среднее квадратическое отклонение: ", data.std(axis=1))
reshaped = maxForRows.reshape((-1, 1))
new_df = np.hstack((df, reshaped))
new_df


Минимальное:  [ 1.    0.54  1.67  4.63  2.42  5.04  7.25  5.21 13.04  3.29  3.71  5.75
  0.42  3.67  4.12  9.96 10.5   9.71  3.08  8.46  2.62  0.33  3.42  8.42
  9.75  9.38  7.58  0.33  3.25 10.58  4.17  7.62  4.67  1.38  1.13  4.58
  9.13  8.5   4.5   1.96  1.54 11.46  4.58  2.25  4.75  0.87  1.21  0.04
  6.21 17.   13.21  8.63 10.92  6.34  1.87  0.21  3.25  3.5   4.75  4.04
  2.92  2.5   6.08  4.75  0.71  0.25  1.42  3.83  3.71  5.91  6.04  2.92
  1.71  4.96  9.21 11.54  4.5   2.92  4.08  7.62  9.    2.62  1.75  1.75
  2.33  1.04  2.42  5.96  8.54  9.42  4.33  0.29  0.29  1.17  3.79  5.37
  1.63  5.04  8.33  4.08 11.71 12.08  5.    9.04  9.75  3.13  2.25  4.67
  5.88  6.58  7.71 10.13  5.04  5.75  7.58  3.54  6.38  6.17  0.71  0.33
  0.63  3.75  2.    0.33  0.29  0.96  1.33  2.54  5.83  7.87  2.29  5.
  3.96  5.04  2.58  7.04  6.17  8.46  1.79  1.96  1.38  2.67  7.96  7.41
  6.38  2.88  6.5   3.96  5.13  7.58  4.04  2.17  6.34  7.21  2.62  2.62
  0.21  1.17  2.21  3.75  3.04  1.29  2

array([[69.  ,  1.  ,  1.  , ...,  9.17, 16.71, 16.71],
       [69.  ,  1.  ,  2.  , ...,  8.17, 13.29, 13.29],
       [69.  ,  1.  ,  3.  , ..., 11.96, 16.17, 16.17],
       ...,
       [69.  , 12.  , 29.  , ..., 13.75, 25.04, 25.04],
       [69.  , 12.  , 30.  , ..., 11.5 , 27.84, 27.84],
       [69.  , 12.  , 31.  , ..., 11.17, 17.41, 27.71]])

### 6 задание
Для каждого дня найдите точку с наибольшем значением скорости ветра. Выведите массив найденных номеров реперных точек (массив целых чисел).

In [123]:
print("Максимальные индексы: ", data.argmax(axis=1))

Максимальные индексы:  [11 11 11 11 11  2 11 11 11  2  1 11 11  1 10 11  1  1 11  2 10 11 10 10
 10  0  0 11 11 11 11 11 11 10 11 11 10 11 11 11 11 11  0  2 11  2  0 11
  0 11 11 11 11 11 11 11  2  2 11  2  0  2  2  0  0 11 11 11 11 11 11 11
 11 11 11 11 11 11 11 11 11  2 11  2  2  2  6 11  4  0 11 11 10  2  2  0
  0 10  0 11  0 11  0  4  0 11  2 11  0 11 11  0 10  0  4  1 10  0 11 11
 11 11 11 11  1 11 10 10  0 10 10  1 11 10 10  0 11 11  4  4  2  0 11 11
 11 11  0 11  2  0  0 11 10  0  2 11 10 10  0  2  2  2 10  0  2 11  0 11
 10  1  0 11 11 11 10 11 11 11 10 10 10 10 11 11 11 11 11  0  0  4 11 11
 10 11 11  0 11 11 10 11 10 10 11 11 10 10 10 10  0 11 10  1 11  0  1 10
 11 10 11 11 10 11 10  2  0 11 10  0 10 10 10 11 11 11 11 11 11  0 11  0
 11  0  2  2  2  2 10 11  2 10 10 11  0  0 10  0  2  2 11  2  2  2 11 11
 11 10 11 11 11 11 11 11 11 11 11 10 10 11 10 11  1  1  4  1  1  2 10 10
 10 11 11 10  4 11 11 10 11 11 11 11 11 11 11 11 11 11  0 11 11  0 11 11
  1 11  2 11 11  2 11 11 11 

### 7 задание
Найдите год, месяц и день, который была зафиксирована самая большая  скорость ветра. Выведите найденную дату.

In [125]:
maxIndexRow = data.max(axis=1).argmax()
maxDay = df[maxIndexRow]
print(int(maxDay[2]), int(maxDay[1]), int(maxDay[0]))

19 2 69


### 8 задание
Найдите среднюю скорость в январе для каждой реперной точки.  Выведите полученные значения.

In [126]:
janData = df[:31,3:]
print(janData.mean(axis=0))

[12.82483871 12.25176833 11.46706452  7.29544575 10.55709677  6.49382405
  9.83041056  8.4841349   8.64041056  9.57449267 13.4446129  16.58404692]


### 9 задание
Сохраните получившийся датасет в csv файл. Проследите, чтобы целые числа  были сохранены в целочисленном формате, без нулей в дробной части.  Каждое число с плавающей точкой сохраните с точностью ровно в 4 знака   после точки.

In [127]:
fmt = ['%d'] * 3 + ['%.4f'] * 13
np.savetxt('output.csv', new_df, delimiter=",", fmt=fmt)

### 10 задание
Посчитайте среднюю скорость ветра для каждого месяца в датасете.  Выведите полученные значения.

In [128]:
for month in range(1, 13):
    monthData = df[df[:, 1] == month][:, 3:]
    print(month, monthData.mean())

1 10.620678885630499
2 11.223787337662337
3 9.315249755620723
4 9.82684696969697
5 7.613002443792767
6 7.96622861952862
7 9.025506842619746
8 8.889809710003258
9 8.056203198653199
10 10.324983382209188
11 10.645541919191919
12 10.592836265884653
