1. Сгенерировать матрицу размером 4 × 9, заполненную случайными целыми числами из отрезка [0,20] и вывести ее на на экран.

In [56]:
import numpy as np


arr = np.random.randint(low=0, high=21, size=(4, 9))
print(arr)

[[ 3 11 17  1 20 10 15 16  9]
 [ 0 18 15  1  7  0  7 13  5]
 [ 9 20 17 12 17  1  2 12 12]
 [ 5 12 10 18 19 13  8 20 13]]


2. Вывести на экран элемент с индексами [2, 6].

In [58]:
print(arr[2, 6])

2


3. Вывести на экран столбец матрицы под номером 3.

In [59]:
print(arr[ : , 2])

[17 15 17 10]


4. Вывести на экран каждый второй элемент третьей строки матрицы.

In [60]:
print(arr[2][1 : : 2])

[20 12  1 12]


5. Вывести на экран элементы последнего столбца в обратном порядке.

In [61]:
print(arr[ : , -1][-1 : : -1])

[13 12  5  9]


6. Изменить форму матрицы с 4 × 9 на 6 × 6.

In [62]:
reshaped_arr = arr.reshape(6, 6)
print(reshaped_arr)

[[ 3 11 17  1 20 10]
 [15 16  9  0 18 15]
 [ 1  7  0  7 13  5]
 [ 9 20 17 12 17  1]
 [ 2 12 12  5 12 10]
 [18 19 13  8 20 13]]


7. Возвести каждый элемент матрицы в заданную степень.

In [63]:
degree_arr = reshaped_arr ** 2 
print(degree_arr)

[[  9 121 289   1 400 100]
 [225 256  81   0 324 225]
 [  1  49   0  49 169  25]
 [ 81 400 289 144 289   1]
 [  4 144 144  25 144 100]
 [324 361 169  64 400 169]]


8. Найти минимум на главной диагонали.

In [64]:
print(np.diagonal(degree_arr).min())

0


9. Найти максимальный элемент в предпоследнем столбце.

In [65]:
print(degree_arr[ : , -2].max())

400


10. Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.

In [66]:
zip_arr = degree_arr.reshape(-1)
sorted_arr = np.sort(zip_arr)[-1 : : -1]
print(zip_arr)
print(sorted_arr)
bool_arr = zip_arr == sorted_arr
print(bool_arr.min())

[  9 121 289   1 400 100 225 256  81   0 324 225   1  49   0  49 169  25
  81 400 289 144 289   1   4 144 144  25 144 100 324 361 169  64 400 169]
[400 400 400 361 324 324 289 289 289 256 225 225 169 169 169 144 144 144
 144 121 100 100  81  81  64  49  49  25  25   9   4   1   1   1   0   0]
False


11. Подсчитать произведение ненулевых элементов на побочной диагонали.

In [67]:
anti_diagonal = np.fliplr(degree_arr).diagonal()
non_zero_elements = anti_diagonal[anti_diagonal != 0]
print(np.prod(non_zero_elements))

21406537958400


12. Создать массив из случайных целых чисел из [-20, 20] размерностью 15

In [68]:
new_arr = np.random.randint(low=-21, high=21, size=15)
print(new_arr)

[  1  19 -10  11   3   1  -1  19 -13  13   2 -11   4  -6 -11]


13. Выведите только положительные элементы массива

In [70]:
print(new_arr[new_arr > 0])


[ 1 19 11  3  1 19 13  2  4]


14. Посчитайте количество четных элементов в массиве

In [69]:
print(len(new_arr[new_arr % 2 == 0]))

4
