1. Сгенерировать матрицу размером 4 × 9, заполненную случайными целыми числами из отрезка [0,20] и вывести ее на на экран.

In [1]:
import numpy as np


arr = np.random.randint(low=0, high=21, size=(4, 9))
print(arr)

[[ 3  8 19  1 15 13 11  6 11]
 [ 3 10  5 12 10 16  4  3 13]
 [14 10 14  2  7  6  1  2 20]
 [ 3  4 11 14  4  7 13  7  7]]


2. Вывести на экран элемент с индексами [2, 6].

In [2]:
print(arr[2, 6])

1


3. Вывести на экран столбец матрицы под номером 3.

In [3]:
print(arr[ : , 2])

[19  5 14 11]


4. Вывести на экран каждый второй элемент третьей строки матрицы.

In [4]:
print(arr[2][1 : : 2])

[10  2  6  2]


5. Вывести на экран элементы последнего столбца в обратном порядке.

In [15]:
print(arr[ ::-1 , -1])

[ 7 20 13 11]


6. Изменить форму матрицы с 4 × 9 на 6 × 6.

In [6]:
reshaped_arr = arr.reshape(6, 6)
print(reshaped_arr)

[[ 3  8 19  1 15 13]
 [11  6 11  3 10  5]
 [12 10 16  4  3 13]
 [14 10 14  2  7  6]
 [ 1  2 20  3  4 11]
 [14  4  7 13  7  7]]


7. Возвести каждый элемент матрицы в заданную степень.

In [7]:
degree_arr = reshaped_arr ** 2 
print(degree_arr)

[[  9  64 361   1 225 169]
 [121  36 121   9 100  25]
 [144 100 256  16   9 169]
 [196 100 196   4  49  36]
 [  1   4 400   9  16 121]
 [196  16  49 169  49  49]]


8. Найти минимум на главной диагонали.

In [8]:
print(np.diagonal(degree_arr).min())

4


9. Найти максимальный элемент в предпоследнем столбце.

In [9]:
print(degree_arr[ : , -2].max())

225


10. Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.

In [10]:
zip_arr = degree_arr.reshape(-1)
sorted_arr = np.sort(zip_arr)[-1 : : -1]
print(zip_arr)
print(sorted_arr)
bool_arr = zip_arr == sorted_arr
print(bool_arr.min())

[  9  64 361   1 225 169 121  36 121   9 100  25 144 100 256  16   9 169
 196 100 196   4  49  36   1   4 400   9  16 121 196  16  49 169  49  49]
[400 361 256 225 196 196 196 169 169 169 144 121 121 121 100 100 100  64
  49  49  49  49  36  36  25  16  16  16   9   9   9   9   4   4   1   1]
False


11. Подсчитать произведение ненулевых элементов на побочной диагонали.

In [11]:
anti_diagonal = np.fliplr(degree_arr).diagonal()
non_zero_elements = anti_diagonal[anti_diagonal != 0]
print(np.prod(non_zero_elements))

41550745600


12. Создать массив из случайных целых чисел из [-20, 20] размерностью 15

In [12]:
new_arr = np.random.randint(low=-21, high=21, size=15)
print(new_arr)

[ -5 -16  20   9   0  13 -14 -18  20 -21  10 -15  18 -15   6]


13. Выведите только положительные элементы массива

In [13]:
print(new_arr[new_arr > 0])


[20  9 13 20 10 18  6]


14. Посчитайте количество четных элементов в массиве

In [16]:
print(len(new_arr[new_arr % 2 == 0]))

9
